sudo: required
services:
  - docker

before_install:
  - docker build -t keinh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true keinh/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "docker-reactq"
  env: "Dockerreactq-env"
  bucket_name: "elasticbeanstalk-us-east-2-770978900144"
  bucket_path: "docker-reactq"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY